# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_url = "ubuntu/trusty64"
  config.vm.box = "ubuntu/trusty64"

  # config.vm.network :forwarded_port, guest: 80, host: 8066
  # config.vm.network :forwarded_port, guest: 3306, host: 3306
  config.vm.network :private_network, ip: "192.168.13.27"

  config.vm.synced_folder ".././", "/app", {:mount_options => ['dmode=777','fmode=777'], :owner => "www-data", :group => "www-data"}

  config.vm.provider :virtualbox do |vb|
    vb.name = "app_ci_sandbox"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app", "1"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    vb.customize ["modifyvm", :id, "--chipset", "ich9"]
    vb.customize ["modifyvm", :id, "--pae", "on"]
  end

  config.vm.define :app_ci_sandbox do |t|
  end

  config.vm.hostname="app.jpserquina.com"

  # Install apache from bootstrap
  config.vm.provision :shell, :path => "bootstrap.sh"

end
